server:
  port: 8081
logging:
  config: classpath:log4j2.xml
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    data: classpath*:schema/data/*.sql
    schema: classpath*:schema/sql/*.sql

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
